ci: Use correct helper image even if both are built simultaneously
Fixes: 5ddb3fb2f173e7873e1d9ce52c416fe055b8e74a

Currently, if both images are built together one of the
image will have a default value since we set tag for
both the images in each matric run. This change ensures
we only set the default value when needed and not in each
matric run.

Signed-off-by: Qasim Sarfraz <qasimsarfraz@microsoft.com>

test

Signed-off-by: Qasim Sarfraz <qasimsarfraz@microsoft.com>

diff --git a/.github/workflows/inspektor-gadget.yml b/.github/workflows/inspektor-gadget.yml
--- a/.github/workflows/inspektor-gadget.yml
+++ b/.github/workflows/inspektor-gadget.yml
@@ -788,8 +788,8 @@ jobs:
     name: helper images
     runs-on: ubuntu-latest
     outputs:
-      dnstester_image: ${{ steps.image-tag.outputs.dnstester || env.DEFAULT_DNSTESTER_IMAGE }}
-      ebpf_builder_image: ${{ steps.image-tag.outputs.ebpf-builder || env.DEFAULT_EBPF_BUILDER_IMAGE }}
+      dnstester_image: ${{ steps.image-tag.outputs.dnstester }}
+      ebpf_builder_image: ${{ steps.image-tag.outputs.ebpf-builder }}
     permissions:
       # allow publishing container image
       # in case of public fork repo/packages permissions will always be read
@@ -815,6 +815,17 @@ jobs:
               - "cmd/common/image/Makefile.build"
     steps:
     - uses: actions/checkout@v4
+    - name: Prepare default image
+      id: default-image
+      run: |
+          if [ ${{ matrix.image.name }} == "dnstester" ]; then
+            echo "default-image=${{ env.DEFAULT_DNSTESTER_IMAGE }}" >> $GITHUB_OUTPUT
+          elif [ ${{ matrix.image.name }} == "ebpf-builder" ]; then
+            echo "default-image=${{ env.DEFAULT_EBPF_BUILDER_IMAGE }}" >> $GITHUB_OUTPUT
+          else
+            echo "Default image not found for ${{ matrix.image.name }}. Exiting."
+            exit 1
+          fi
     - uses: dorny/paths-filter@v3
       id: filter
       with:
@@ -855,9 +866,12 @@ jobs:
         platforms: ${{ matrix.image.platform }}
     - name: Save ${{ matrix.image.name }} image tag output
       id: image-tag
-      if: steps.build-image.outputs.digest != ''
       run: |
-        echo "${{ matrix.image.name }}=${{ steps.set-repo-determine-image-tag.outputs.container-repo }}:${{ steps.set-repo-determine-image-tag.outputs.image-tag }}" >> $GITHUB_OUTPUT
+        if [ -n "${{ steps.build-image.outputs.digest }}" ]; then
+          echo "${{ matrix.image.name }}=${{ steps.set-repo-determine-image-tag.outputs.container-repo }}:${{ steps.set-repo-determine-image-tag.outputs.image-tag }}" >> $GITHUB_OUTPUT
+        else
+          echo "${{ matrix.image.name }}=${{ steps.default-image.outputs.default-image }}" >> $GITHUB_OUTPUT
+        fi
 
   build-examples:
     name: example
